name: Playwright UI + API Tests (Manual)

on:
  workflow_dispatch:


defaults:
  run:
    working-directory: PlaywrightTests

jobs:
  playwright-tests:
    runs-on: windows-latest
    environment: LocalizationSandbox 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          # workspace köküne göre path
          cache-dependency-path: PlaywrightTests/package-lock.json

      - name: Install dependencies (npm ci)
        shell: pwsh
        run: |
          if (Test-Path package-lock.json) {
            Write-Host "Found package-lock.json — running npm ci"
            npm ci --no-audit --no-fund --prefer-offline
          } else {
            Write-Host "No package-lock.json — running npm install"
            npm install --no-audit --no-fund
          }

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run UI tests
        working-directory: PlaywrightTests  
        env:
          BC_BASE_URL: ${{ secrets.BC_BASE_URL }}
          BC_USERNAME: ${{ secrets.BC_USERNAME }}
          BC_PASSWORD: ${{ secrets.BC_PASSWORD }}
          TOTP_SECRET: ${{ secrets.TOTP_SECRET }}
          BC_COMPANY_ID: ${{ secrets.BC_COMPANY_ID }}
          BC_ENVIRONMENT: ${{ secrets.BC_ENVIRONMENT }}
        run: |
          npx playwright test --project=chromium-tests

  

      - name: Run API tests (optional)
        continue-on-error: true  
        env:
          BC_TENANT_ID: ${{ secrets.BC_TENANT_ID }}
          BC_CLIENT_ID: ${{ secrets.BC_CLIENT_ID }}
          BC_CLIENT_SECRET: ${{ secrets.BC_CLIENT_SECRET }}
          BC_COMPANY_ID: ${{ secrets.BC_COMPANY_ID }}
          BC_BASE_URL: ${{ secrets.BC_BASE_URL }}
          BC_ENVIRONMENT: ${{ secrets.BC_ENVIRONMENT }}
          
        run: |
          npx playwright test --project=api
          
      - name: Generate Allure report
        if: always()
        run: npx allure generate allure-results --clean -o allure-report    
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: |
            PlaywrightTests/allure-report
            PlaywrightTests/allure-results
          if-no-files-found: warn
          retention-days: 7
      
      - name: Upload Playwright HTML report
        if: always()   # testler fail olsa bile rapor gelsin
        uses: actions/upload-artifact@v4
        with:
          name: playwright-reports
          path: PlaywrightTests/playwright-report
          if-no-files-found: warn
          retention-days: 7
